### PR TITLE
Update to v0.6.0

### PR DESCRIPTION
**Pull request by stuartcampbell**

### CODE REVIEW

**Review by ericdill — APPROVED** [review]

**Comment by ericdill** [comment]
Closing in favor of the sphinx_bootstrap_theme feedstock (i.e., the one with underscores)

**Comment by stuartcampbell** [comment]
@ericdill No problem - Just wondering why was the 'underscores' feedstock created after this repo and not just rename this one ?  Seems silly to have 2 ?

**Comment by ericdill** [comment]
@stuartcampbell -- the history here is that one of them was created first (- or _, i don't remember which, let's just say `-` for arguments sake) and then someone else added `_` through staged recipes. `_` then made it through the staged recipes review process without the reviewer(s) realizing that `-` had already been added

**Comment by stuartcampbell** [comment]
@ericdill that's what I figured.  When I created my PR is did it against this one as this one was the older.  But it's all good.

Maybe conda-forge should have a naming standard / recommendation for this type of thing ?  It seems to be random at the moment. :-)

**Comment by ericdill** [comment]
@stuartcampbell -- I agree in principle. In practice this `sphinx-bootstrap-theme` vs `sphinx_bootstrap_theme` is the only instance of the `-` vs `_` making it through staged recipes (that I am aware of!).

If you think we should keep this repo (`-`) and delete the other one (`_`) that's fine too. I don't really have a strong opinion here and it's a huge PITA to actually delete a repo. There's like 8 steps that need to be done so if you've got a preference for `_` vs `-`, I'm happy to respect that

**Pull request closed without merging**
